### ISSUE TITLE
Http4sSpec

### ISSUE THREAD

**Issue by keshav-elevio** [http4s/http4s#1024]
Hi,
   How do I write integration tests? I have added dependency to "org.http4s" %% "http4s-testing"     % "0.15.6" % "test" but It does not have class Http4sSpec.

Help would be much appreciated.

Keshav

**Comment by rossabaker** [comment]
`Http4sSpec` is for internal tests.  It brings along a dependency specs2, whereas the testing project is agnostic to test frameworks.

I think `Http4sMatchers` would have some value for external users, but it also has a dependency on specs2.  I'd like to think out how we could make it useful for scalatest users as well.

**Comment by keshav-elevio** [comment]
exactly, it would be great to be able to write integration tests. Similar to ScalatraSuite

**Comment by rossabaker** [comment]
Can anyone point to a guide for making matchers useful in both scalatest and specs2?  If so, this is easy: things go into http4s-testing.  If not, we need a parallel http4s-specs2 and http4s-scalatest, which is something I've done on other projects, and it's a pain.

**Comment by PhillipTaylor** [comment]
I wanted to write a few integrations tests for my app, checking that url handling is sane for various configurations but am running into the problem that once a BlazeServer is constructed it's bound to a port and the server.shutdown won't work as anticipated. It seems that shutting down the Server is achieved by a JVM shutdown hook but the JVM won't be shutting down during the the test runs, so I am limited to only being able to run a single integration test. I'm unsure of how I can achieve what it is I'm trying to do.

Ideally there would be a way to send a request into a Blaze server without having to bind to a port at all (so that I can run tests in Jenkins in parallel too). Can someone assist me on if my approach is sane?

**Comment by reactormonk** [comment]
I'd do as much as possible on `Service`, if that helps.

**Comment by PhillipTaylor** [comment]
Yeah this approach seems to be more than appropriate, thank you.
