### ISSUE TITLE
Parameterization of the effect

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#1129]
We get asked now and then why http4s is specialized on Task instead of parameterized over its effect.  Parameterization certainly seems like the right thing to do, and it's very possible, but it complicates the code.  Namely, `Request` and `Response` get a type parameter, `EntityEncoder` and `EntityDecoder` get a second, and parameters spread from there.

With all the talk of effect abstractions swirling around, the topic has come up again.  I tried one to prototype it one more time, and [core mostly compiles](https://github.com/http4s/http4s/compare/master...rossabaker:parameterized-effect).

Pros:
* People who choose a different effect from us get a native experience.
* People might do clever things with transformers over the same base effect as us.

Cons:
* Raises the barrier to using the library.
* Raises the barrier to contribution.

This experiment has reinforced my belief it's possible without persuading me that it's prudent.  If someone can bring forth a very compelling use case, I'm willing to pursue this further.  If not, let this ticket be a marker for an FAQ entry about why it's not parameterized.

**Comment by pchiusano** [comment]
I don't know much about http4s, but I suspect making it effect polymorphic is the "right" choice, that is where I would start, and I was surprised to learn that it's hardcoded. Here are a couple other points beyond what you've mentioned -

* When you're polymorphic in the effect type, you have more free theorems. In fact, I bet if you did an audit of all the functions in http4s you'd find lots of functions that could be either fully polymorphic or have some tighter bound (like that don't need a `Concurrent` bound), but which are currently specialized to  `Task`.
* Free theorems are good for correctness and ease of reasoning. If you know how to read type signatures, I would argue they can ENHANCE usability because readers have fewer possibilities to think about when examining a generic function. And developing the skill of reading and writing generic code pays for itself many times over if you do any amount of FP...
* By the way, this is one of the big reasons for FS2. You realize that large amounts of your code does not deal specifically with IO, and can write and easily test that logic independent of IO. And even for code that does IO, you can if you like swap in new IO implementations with different properties (like off the top of my head, how about one that randomly fails actions to test error handling robustness?).
* It's "easy" to take a generic library and specialize it to some particular effect. But you can't go the other direction. So now everything downstream of https has to make the same choice as you if they want to use your library.
* Kind of subjective, but I think middleware libraries like http4s should not be opinionated about anything they don't need to be, since your users may use your library in ways you cannot anticipate and it's great to give them more free rein. If there is like a big cost to being agnostic about something, then that's one thing and maybe you make a tradeoff. If it's just an additional type parameter being propagated around, that is about as low cost as it gets (unless it causes horrible type inference) and in some ways it's a benefit.

The way I'd approach questions of usability is - will the library be better for people who spend more than 16 hours using it, and who are willing to invest a little bit of time to understand what they need to be most productive with it? If you are making the library "worse" for people who use it more heavily and care enough to learn about it, in order to make it more marketable or give it some surface appeal... well that is not a great tradeoff to make.

Okay, but having said all that... I am talking in generalities and you are the library author and have direct experience and probably better idea of costs / benefits. :)

**Comment by rossabaker** [comment]
Thanks, Paul.  I have made a few abortive attempts at this on the scalaz-stream branch.  fs2 avoids specialization in functions that scalaz-stream specialized on `Task`, so the payoff is now higher.  The fs2 port is already a breaking change, so I think this deserves one last thorough evaluation.

I got core, dsl, jawn, and circe [compiling](https://github.com/http4s/http4s/compare/master...rossabaker:f), which is enough to try to port most of an [example service](https://github.com/http4s/http4s/compare/master...rossabaker:f#diff-96dc15abab0def98703dc68cd1886461).

`HttpService { ... }` becomes `HttpService[Task] { ... }`.  That's not bad at all.  Then we see that inference is hit and miss:

Code | Compiles | Notes
---|---|---
`Ok("ping")` | ✅ |
`Ok("ping").putHeaders(Header(header))` | ❌ | diverging implicits
`Response(Ok).withBody("ping")` | ✅ |
`Response(Ok).withBody("ping").putHeaders(header))` | ❌  | diverging implicits
`Response[Task](Ok).withBody("ping").putHeaders(header))` | ✅ |

The second construction is quite common.  We can retain the nice syntax and prevent a large breaking change by retaining the specialization of `org.http4s.dsl.ResponseGenerator`s on `Task`.

Now how about other effects?

Specialized: every response needs to mention the effect:

```
  HttpService[Future] {
    case req @ GET -> Root / "pong" =>
      Response[Future](Ok).withBody("pong")
    case req @ GET -> Root / "nope" =>
      Future(Response(NoContent))
  }
```  

I'll bet we could make an "abstract DSL" that supported imports from an object that makes the parameter concrete.  Then services that choose a different effect could still get all the syntactic sugar.

Polymorphic:

```
  def service[F[_]](implicit F: Applicative[F]) = HttpService[F] {
    case req @ GET -> Root / "pong" =>
      Response[F](Ok).withBody("pong")
    case req @ GET -> Root / "nope" =>
      F.pure(Response(NoContent))
  }
```

This is looking more viable than my previous attempts, especially if we keep http4s-dsl biased toward `Task`.  http4s-core is designed to boil HTTP down to a simple Kleisli, and http4s-dsl to make one easy way of creating those Kleislis, so a more abstract core and specialized DSL seems legitimate.

What does this do to rho?

**Comment by rossabaker** [comment]
I'm more interested in debate than votes, but maybe the latter can beget the former: https://twitter.com/http4s/status/856546435583619074

**Comment by djspiewak** [comment]
Why does `withHeaders` diverge?

I think @pchiusano's point is an important one: theorems for free are really valuable, *especially* for contributors who are accustomed to reasoning about polymorphic signatures.  Type errors are a concerning point, and obviously a lot of people *aren't* accustomed to reasoning about polymorphic signatures.

**Comment by rossabaker** [comment]
I think the pattern might be that implicits diverge when it needs to infer the effect before the final invocation.  I tried replacing `putHeaders` with simple `map` or `flatMap` and got similar results.  In the first two passes, the only inference of `F` is the final call.  In the third pass, we are explicit at the beginning and the `Task` is inferred through the rest of the expression.  In the two failures, it needs to know `F` before it gets to the final call, and the fact a `Task` is needed doesn't seem to backtrack past the last call.

**Comment by ChristopherDavenport** [comment]
With the milestone releases on 0.18 I think we can close this.
