### ISSUE TITLE
Blaze client: Time to first byte timeout

### ISSUE THREAD

**Issue by scottcarey** [http4s/http4s#1349]
A time to first byte (TTFB) timeout in the BlazeClient would be very useful.  In my case, I have requests that are naturally of very long duration, streaming large chunks of data, but the server might be unresponsive.   A very long timeout is needed for the total request time, but a short timeout to first byte is desired.

I don't care if it is time to the first byte of the body, or time to the headers being returned, but I can see how both could be useful to others.

**Comment by rossabaker** [comment]
#1350 is a server change that flushes the header as soon as it's available.

The idle timeout on the client is reset by both reads and writes.  A TTFB timeout would be trivial if writes didn't cancel the pending idle timeout.  We'll need some additional state somewhere to track the first read.

**Comment by rossabaker** [comment]
Should a first-byte timeout ever exceed the idle timeout, or only more tightly constrain it?  This could impact the right design.

**Comment by scottcarey** [comment]
I'm not sure.   When I think about an HTTP request, I come up with 4 phases of the request that could potentially all have independent timeouts (though that would be overkill):

1.  Establishing the TCP connection or obtaining it from a pool.
2.  Issuing the request and waiting for HTTP response headers.
3.  Waiting for the first byte in the body (if the result has a body).
4.  Waiting for the request to complete.

For my purposes, a timeout for either 2 or 3 independent of 4 is what I need. It could encompass #1 as well.   I need to differentiate between a slow network (delays in the body) from a slow server (delays to first byte or headers).  I would probably configure a 5 second TTFB timeout and 30 second data transfer idle timeout.

The most flexible thing is to have the two timeouts be independent, one applying before the first server response packet (headers, #2 above), the other applying after.

This can be viewed as the same idle timeout with different restrictions in different phases, or as two independent timeouts.

One might have a use case where a TTFB timeout is longer than the idle timeout for the duration of the response.  Perhaps someone is working with busy or eagerly queuing servers on a fast network (like a computing cluster), so long initial delays are expected but once established fast transfers are expected.  This is the opposite of my use case -- servers should generally reply quickly unless unhealthy (we return 'too busy' aggressively, so long delays to first byte indicate something is wrong), but the requests can reach across the globe over slow networks.

I don't have a strong opinion on which way to go, especially as I don't know if there is a large difference in implementation complexity.  My gut says that all else being equal, two independent timeouts that do not constrain each other is a bit better.

**Comment by rossabaker** [comment]
> 1. Establishing the TCP connection or obtaining it from a pool.

This is an area for improvement.  (TLS handshake is another).

> 2. Issuing the request and waiting for HTTP response headers.
> 3. Waiting for the first byte in the body (if the result has a body).

There are three potentially interesting events here:

- the first byte of the header
- the `\r\n\r\n` that terminates the header
- the first byte of the body

#1350 will flush the first byte of the header aggressively in a blaze-server.  It will withhold the `\r\n\r\n` with the first byte of the body, waiting to see if the first chunk is the last chunk and can stick to `Content-Length` instead of `Transfer-Encoding`.  In other servers, the gap may be shorter between the first two than the last two.

I think we need either a time-to-first-byte or a time-to-response-header-complete.  I think either would be sufficient for your case if the server aggressively completed the header.  I've seen response header complete timeouts in other clients.  Maybe that's the way to go, and blaze-server should more aggressively render the `\r\n\r\n` even if it triggers chunked encoding.

I think an idle timeout would cover the first byte of the body well: the first header byte might be special, but the first body byte should be treated about the same as other body bytes.

> 4. Waiting for the request to complete.

This one is well covered by our existing `requestTimeout`.

**Comment by rossabaker** [comment]
Some precedent for timeouts in other clients:
* [Python requests](http://docs.python-requests.org/en/master/user/advanced/#timeouts)
* [curl](https://unix.stackexchange.com/a/94612)
* [Go net/http](https://blog.cloudflare.com/the-complete-guide-to-golang-net-http-timeouts/#clienttimeouts)
* [async-http-client](https://github.com/AsyncHttpClient/async-http-client/blob/master/client/src/main/java/org/asynchttpclient/AsyncHttpClientConfig.java), search "timeout"
* [Apache HTTP Core](https://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/client/config/RequestConfig.Builder.html), search "timeout"
* [Play WS](https://www.playframework.com/documentation/2.5.x/ScalaWS#Configuring-Timeouts)

**Comment by ChristopherDavenport** [comment]
Has this been addressed by #1350 and #1352?

**Comment by rossabaker** [comment]
Yeah.  I think the above links are good for further discussion, but I think we've got a solution in 0.17.0-RC3.
