### ISSUE TITLE
server-metrics don't handle requests to the `metricsService` correctly.

### ISSUE THREAD

**Issue by agarbutt** [http4s/http4s#1606]
I tried out the server-metrics package today and its [BlazeServerExample](/http4s/http4s/blob/master/examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeMetricsExample.scala).  Nice work, it looks really promising.  

An oddity that I noticed was that the `active_requests` would increment but not decrement when the "/metrics" endpoint is invoked. It seems that the code in Metrics HttpMiddleware would increment but because the `prefix` was not found, it would never call funciton `generalMetrics`.

**Comment by rossabaker** [comment]
I think you're right.  Would you be interested in taking a crack at fixing this?  I think the problem is right around [here](https://github.com/Verizon/knobs/blob/2ee0438bcfa638c4bc1cd47a854506903e11f347/core/src/main/scala/knobs/package.scala#L99).

**Comment by rossabaker** [comment]
@ChristopherDavenport said he'd try this after dinner.  If so, awesome.  If not, please kick back to me.

**Comment by rossabaker** [comment]
Behavior I'd expect:

1. GET /http4s/metrics does not increment counters (it’s not wrapped in the middleware)
2. GET /http4s/metrics does not leave a dangling active request
3. GET /http4s/dfdajkfldajfklddasfadskl does not leave a dangling active request. (This is one where a wrapped service returns None).
4. GET /http4s/djfkldajfkldadfadfjkasdf increments 4xx. (debatable, but consistent with error handler: it anticipates what the backend is going to do, and can’t know what fallback composed services does)
5. GET /http4s/ping increments 200 and does not leaving dangling active request

Quirky case that @rsoeldner found today:

1. GET /http4s/metricsadfjdasfjadklfadsfjkladsfjk returns 200.  This is because the router does simple prefix matching without regard to segments _and_ MetricsService matches all GET requests, not just Root.  I think which one, or both, of these to change is a separate issue.
