### ISSUE TITLE
Stackoverflow when implicitly creating an EntityEncoder for an implicit circe Encoder

### ISSUE THREAD

**Issue by jadlr** [http4s/http4s#1648]
I brought this up in the gitter channel and received great help from @SystemFw. 

I'm adding it as an issue so that other people who might stumble over it are warned and also for tracking a possible fix for it.

If you create an implicit `EntityEncoder` from an implicit `Encoder` like so:
```scala
implicit def entityEncoder[A: Encoder]: EntityEncoder[F, A] = jsonEncoderOf[F, A]
```
You will get a `StackOverflowError`. 

The solution (thanks @SystemFw) is to define the implicit like this:

```scala
  implicit def entityEncoder[A](implicit enc:  Encoder[A], ev: EntityEncoder[F, String]): EntityEncoder[F, A] = jsonEncoderOf[F, A](ev, implicitly[Applicative[F]], enc)
```

**Comment by gvolpe** [comment]
For the record, this seems to work fine for me but I'm not sure about the correctness:

```scala
implicit def jsonEncoder[A <: Product : Encoder, F[_]: Sync]: EntityEncoder[F, A] = jsonEncoderOf[F, A]
```

**Comment by SystemFw** [comment]
@gvolpe Counterexample

```scala
object Ex {
  import cats.effect._
  import io.circe._
  import io.circe.generic.auto._
  import org.http4s._
  import org.http4s.circe._

  implicit def jsonEncoder[A <: Product : Encoder, F[_]: Sync]: EntityEncoder[F, A] = jsonEncoderOf[F, A]

   case class Yo()

  class Foo[F[_]: Effect] {
    Encoder[String] // ok
    EntityEncoder[F, String] // ok
    Encoder[Yo] // ok
    EntityEncoder[F, Yo] // ok
    EntityEncoder[F, Int] // doesn't compile
  }
}
```

**Comment by gvolpe** [comment]
Okay so it works fine for any case class and String only... Interesting.

**Comment by SystemFw** [comment]
It will also break (I think) for sealed traits that don't extend Product, and `object`s that aren't `case objects`

**Comment by gvolpe** [comment]
Normally I define my sealed traits that are ADT's by extending `Product with Serializable` to help the type inference system. Not sure when one would try to get an `EntityEncoder` for an `object` though but it's good to keep this in mind.

**Comment by rossabaker** [comment]
Do we have plans to do anything about this?  Fix it?  FAQ it?

**Comment by kevinmeredith** [comment]
Could you please explain the reason for the `StackoverflowError`, @SystemFw, on:

```
implicit def entityEncoder[A: Encoder]: EntityEncoder[F, A] = jsonEncoderOf[F, A]
```

?

Thanks!

**Comment by SystemFw** [comment]
@kevinmeredith sure. Let's look at the signature of `jsonEncoderOf`:
` def jsonEncoderOf[F[_]: EntityEncoder[?[_], String]: Applicative, A: Encoder]: EntityEncoder[F, A]`

It wants an `Encoder` for `A`, and an `EntityEncoder[F, String]`. So first of all your signature above is making the mistake of not propagating the `EntityEncoder[F, String]` constraint. Normally forgetting to propagate an implicit will cause a compilation error, since the method call needing it will not find it, however in this specific case, to define `entitytEncoder` you call `jsonEncoder`, which looks for an `EntityEncoder[F, String]` and finds...`entityEncoder` (by applying `A` to `String`), which is in turn defined by calling `jsonEncoder`, which looks for an `EntityEncoder[F, String]`, which finds...`entityEncoder` (by applying `A` to `String`), which is in turn defined by....

This infinite recursion causes a stack overflow.

**Comment by kevinmeredith** [comment]
Thanks, @SystemFw, for that detailed explanation!

Why must [jsonEncoderOf](https://github.com/http4s/http4s/blob/master/circe/src/main/scala/org/http4s/circe/CirceInstances.scala#L94) have an `EntityEncoder[F, String]` in implicit scope?

**Comment by rossabaker** [comment]
You know, maybe it shouldn't: maybe we should just refer to it explicitly, with explicit UTF-8 encoding. :thinking:

**Comment by jmcardon** [comment]
You have the choice of a different encoding regardless.

**Comment by rossabaker** [comment]
I thought I remembered JSON requiring a UTF-8 encoding.  It requires a _unicode_ encoding.  

If we provide an implicit string encoder, nothing stops a bizarre encoding. If we provide an implicit charset, nothing stops a bizarre encoding, but we get out of this circle.  If we provide an implicit sealed enum of unicode encodings, we can statically prevent illegal encodings, but, good grief.

**Comment by rossabaker** [comment]
`jsonEncoderOf` no longer takes an `EnityEncoder[F, String]`. I think this is obsolete now.
