### ISSUE TITLE
Connection pool should be based on a Timer

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#1793]
Then we could test things like #1792.

I know @ChristopherDavenport has a lot more problems with the connection pool than that. :laughing:

**Comment by danicheg** [comment]
Actually `PoolManager` has an `Async` constraint and therefore `Temporal` (for 0.23 and 1.0 series). So since `Timer`, as well as the 0.22 series, has gone we need to change issue that `PoolManager` should be based on `Clock` or close it if `Temporal` is enough for testing reasons. Also, CE comes with `TestControl` now, which helps in testing temporal things (it's not a silver bullet, though).
