### ISSUE TITLE
Documentation is unclear about HTTP Client creation

### ISSUE THREAD

**Issue by nadenf** [http4s/http4s#1965]
This section here:

"Note: In production code you would want to use Http1Client.stream[F[_]: Effect]: Stream[F, Client[F]] to safely acquire and release resources. In the documentation we are forced to use .unsafeRunSync to create the client."

It says "we are forced to use" this approach but it is not recommended. Why are you forced to use it ? And why is the documentation not recommending the best approach to creating the client ?

**Comment by rossabaker** [comment]
Great question.  The documentation is generated by sbt-tut, which lets us alternate text and compiled code.  The problem is the code blocks in tut need to be complete (i.e., no open `{`).  We can't intersperse explanatory text with code inside a properly bracketed client.

We need to explain this better, or figure out a hack or enhancement to tut.

**Comment by rossabaker** [comment]
This is hurting us badly on #1993: we can't even create a client with `.unsafeRunSync` anymore.  It's forcing us to do the right thing, but we need to restructure this tut.

Volunteers?

**Comment by armanbilge** [comment]
I think this is fixed. Improved anyway.
https://http4s.org/v0.23/docs/client.html#creating-the-client
