### ISSUE TITLE
CORS headers overwrites existing Vary headers

### ISSUE THREAD

**Issue by yasuba** [http4s/http4s#2003]
My application returns the Vary:Accept header, but when a client makes a request with an Origin header, the http4s CORS object overwrites with Vary:Origin,Access-Control-Request-Methods by using putHeaders:

```
def corsHeaders(origin: String, acrm: String, isPreflight: Boolean)(
          resp: Response[F]): Response[F] = {
        val methodBasedHeader =
          if (isPreflight)
            config.allowedHeaders.map(headerFromStrings("Access-Control-Allow-Headers", _))
          else config.exposedHeaders.map(headerFromStrings("Access-Control-Expose-Headers", _))
        methodBasedHeader
          .fold(resp)(h => resp.putHeaders(h))
          .putHeaders(
            Header("Vary", "Origin,Access-Control-Request-Methods"),
            Header("Access-Control-Allow-Credentials", config.allowCredentials.toString()),
            Header(
              "Access-Control-Allow-Methods",
              config.allowedMethods.fold(acrm)(_.mkString("", ", ", ""))),
            Header("Access-Control-Allow-Origin", origin),
            Header("Access-Control-Max-Age", config.maxAge.toString)
          )
      }
```

I'd like to continue to return Vary: Accept as well as Origin and Access-Control-Request-Methods - are there any issues with this?

**Comment by rossabaker** [comment]
CORS gives me a headache.  Paging @jmcardon, and if nobody else chimes in, I'll take a deeper look this afternoon.

**Comment by jmcardon** [comment]
[So, the W3 section has a quip on the presence of setting `Vary`, but it is not enforced](https://www.w3.org/TR/cors/#resource-implementation). In particular, it's done when `Access-Control-Allow-Origin` is non uniform, thus `Vary` changes for the sake of preventing caching incorrect responses depending on the origin.

So, It's good practice, but it's not enforced by the rfc. We could fix this by either a boolean flag on whether we should set vary (since it's good practice to do so), or check whether `Vary` is manually set before setting it.

Also, I found a bug there:

```scala
            Header("Vary", "Origin,Access-Control-Request-Methods"),
```

It should be `Access-Control-Request-Method`.

**Comment by yasuba** [comment]
@jmcardon - sure, happy to.
