### ISSUE TITLE
Eliminate `Status.register`

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#2015]
This was inherited from our original fork of Spray, many years ago.  It is global, mutable state.  It's fine as an internal mechanism for resolving values to a single reference, but it should not be public API.

**Comment by calvinbrown085** [comment]
Hey Ross, more than happy to pick this up. https://github.com/http4s/http4s/blob/b9a28ddcd335cf5dee60a9f7d3be5bdc12523179/core/src/main/scala/org/http4s/Status.scala#L103

is this as simple as making this `private def` ?

**Comment by rossabaker** [comment]
I think this solves the problem, but we might simplify the implementation a bit more.  We don't really need an `AtomicReferenceArray` anymore, since there can no longer be concurrent additions and updates.  Just an `Array` should suffice.

Either the `AtomicReferenceArray` or `Array` implementations trade space (about 50 of the 600 spots are used) for time (indexed lookup vs. hash lookup).  I think this is a fine trade, but am open to being shown I'm wrong.

**Comment by ghostroad** [comment]
I'm new to http4s. I've been taking a look at this issue, and my first thought was "These should be case objects!" which I realized wouldn't work because they must be created eagerly. 

From reading the code, it seems we want to both maintain a registry of "standard" `Status`es and have the ability to create new, unregistered, ad-hoc ones (e.g., using `Status.fromInt` or `withReason`). Is this the desired behavior? If it is, then something like a private `register` method is needed, for explicitly registering the standard statuses. If not, then registration could be moved into the constructor, making it automatic.

It does seem like an `Array[Some[Status]]` would be a cleaner replacement for the existing registry.

I was also wondering about this spec:

https://github.com/http4s/http4s/blob/b9a28ddcd335cf5dee60a9f7d3be5bdc12523179/tests/src/test/scala/org/http4s/StatusSpec.scala#L43-L47

It seems like an odd thing to check for, since equality for `Status`es only cares about the status code. It would be helpful to have specs that describe this behavior more fully. 

@calvinbrown085, would it be alright if I took a look at this on a new, more up-to-date branch?

**Comment by calvinbrown085** [comment]
@ghostroad Feel free!

**Comment by jmcardon** [comment]
@ghostroad they don't need to be created eagerly, if the array initialization is a static block.

> From reading the code, it seems we want to both maintain a registry of "standard" Statuses and have the ability to create new, unregistered, ad-hoc ones (e.g., using Status.fromInt or withReason). Is this the desired behavior? 

We've spoken about this on gitter, so apologies if it's not indexed well, but:
- `fromInt` is useful for clients, but shouldn't exactly be to create new statuses.
- It was behavior that was allowed before, but we've discussed against it as of late. I'm :+1: with this behavior being obliterated.

>  If not, then registration could be moved into the constructor, making it automatic, and we would no longer incur the risk that @rossabaker mentioned of failing to register a status.

Registration shouldn't be a side effect of the constructor. 

> It does seem like an Array[Some[Status]] would be a cleaner replacement for the existing registry.

Yeah, that would be a nice micro-optimization to avoid bxing them twice, though I think since parseresult is `Either`, `Right` is more appropriate

**Comment by ghostroad** [comment]
Thanks for the clarification! I took a look at the conversation on Gitter. 

I wanted to make sure that I'm understanding you correctly.

1) For an unregistered code, do we want `Status.fromInt` to fail?
2) For a registered code but nonstandard reason, should `Status.fromIntAndReason` also fail? If it is not essentially a factory method for constructing such statuses, I can't conceive of a use for it.
3)`Status.withReason` is only ever used in a spec (the one I refer to above). Should the spec and the method be removed? I'm really inclined to remove both.

Thanks!

**Comment by jmcardon** [comment]
> For an unregistered code, do we want Status.fromInt to fail?

IMO yes.

> For a registered code but nonstandard reason, should Status.fromIntAndReason also fail? If it is not essentially a factory method for constructing such statuses, I can't conceive of a use for it.

This is a good question. I don't have the answer to this one yet, it would be good to see where we're using it.

> 3. The method Status.withReason is only ever used in a spec (the one I refer to above). Should the spec and the method be removed? I'm really inclined to remove both.

If it's literally only for one place and we can replace it in userland, I say we go for it.

**Comment by ghostroad** [comment]
@rossabaker, @jmcardon,  thanks for the clarifications. 

I can see that `forAll { (s: Status, r: String) => s === s.withReason(r) }` is an assertion one would want to make. On the other the hand the spec says: 

https://github.com/http4s/http4s/blob/b9a28ddcd335cf5dee60a9f7d3be5bdc12523179/tests/src/test/scala/org/http4s/StatusSpec.scala#L43-L47

and this appears to be the only current use of `withReason`. As it stands, it produces an entirely new `Status` object with identical properties except for the custom reason. 

It seems that we've agreed to change the behavior so that clients are unable to obtain a `Status` object with a nonstandard code, even if it is between 100 and 599. What isn't yet clear to me is whether it should be possible to create a `Status` with a standard code but nonstandard reason. Both `withReason` and `fromIntAndReason` do this.

As for the original concern expressed in this issue, knowledge of the `registry` shouldn't be available to the outside world. As @calvinbrown085 showed, the `register` method can be safely made private. But there's also `registered`, which yields an iterator over the registered statuses, and this only ever appears to be used for the `Arbitrary[Status]` generator. I propose that we modify the specs and generators (perhaps by using more focused checks) to be able to hide the registry completely.

**Comment by ghostroad** [comment]
Actually I take this last point back, it wouldn't be a good idea to restrict the arbitrariness of the `Status` generator in any way, so `registered` should be kept.

**Comment by ghostroad** [comment]
@rossabaker Thanks for looking at the pull request, and sorry for the misunderstanding. Regarding the proposed behavior of `fromInt`, I'm going by what was suggested by @jmcardon [above](https://github.com/http4s/http4s/issues/2015#issuecomment-415634784): 

>> For an unregistered code, do we want Status.fromInt to fail?

>IMO yes.

Also, [here](https://github.com/http4s/http4s/pull/2020#issuecomment-414167795):

> is there any particular reason why it's an AtomicReferenceArray in the first place over just an array, if we should never mutate it anyway outside the first initialization block? We ruled we're going to stop people from registering custom status codes anyway.
