### ISSUE TITLE
Question: Ready for production?

### ISSUE THREAD

**Issue by sideeffffect** [http4s/http4s#2044]
Hello,
we're considering to use http4s, but we're not 100 % sure of the current status -- for example, the version is still at `0.x`.

 * Is the current stable version `0.18.16` ready to be used in production?
 * Are backwards incompatible changes to be expected?
 * Are significant architectural (although backwards compatible) changes to be expected?
 * Should we wait for `0.19.x`?
 * Or even `1.x` ([which seem far from now](https://github.com/http4s/http4s/milestone/4))

thanks!

**Comment by SystemFw** [comment]
> or example, the version is still at 0.x.

You shouldn't worry about this. Http4s is ready for prod from at least 0.15 

> Is the current stable version 0.18.16 ready to be used in production?

Yes

> Are backwards incompatible changes to be expected?

Yes, major versions (so, 0.19) introduce breaking changes. We try to minimise breakage with deprecations and scalafixes. We do take this seriously.

> Are significant architectural (although backwards compatible) changes to be expected?

Yes, to a certain extent (although the basic philosophy and goals of the project stay the same)

> Should we wait for 0.19.x?

Depending on how quickly you want to get something out, this is an option you should consider. 0.18 is perfectly fine and used in prod by dozens of companies btw, it's just that if you want to minimise breakages, you _might_ (or might not) want to wait

> Or even 1.x

No, I would definitely not recommend this

**Comment by rossabaker** [comment]
I mostly agree with @SystemFw.  More:

* 0.19 should be the last 0.x release series.  The 0.x status of both cats-effect and fs2 has kept us on 0.x.  There are several improvements we'd like before 1.0, though I hope the stabilization of our dependencies means we can focus fully on on those of our integrations with the foundational libraries.
* We've talked a lot about scalafix but never written one.  I still would like one from 0.18.
* I've been using http4s in mission-critical work since 0.8.  The 0.x means you'd be committing to occasional migrations, but not to a perpetually alpha product.

**Comment by SystemFw** [comment]
Speaking of which, if anyone reading this is a scalafix expert (whereby expert I mean "knows a bit of scalafix") please come talk to us! You'd be an instant hero (and perhaps we should advertise this a bit more)

**Comment by rossabaker** [comment]
Scalafix issue: #2045
