### ISSUE TITLE
Core DSL returns 404 when 405 is called for

### ISSUE THREAD

**Issue by wsh** [http4s/http4s#234]
Hi all! First and foremost, thanks for your hard work on http4s. We're using it in production and find it a pleasure to work with.

My teammate noticed something odd. We have a service spec'd out like this

```
def service(...): HttpService = HttpService {
    case req @ GET -> Root => Ok("Hello world!")
    case req @ GET -> Root / "foo" => ...
    case req @ GET -> Root / "bar" => ...
    case req @ GET -> Root / "baz" => ...

    case req @ POST -> Root / "bar" => ...
    case req @ POST -> Root / "baz" => ...
}
```

and we run it with `BlazeBuilder.bindSocketAddress(new InetSocketAddress(config.port)).mountService(svc, "/").run.awaitShutdown`. We'd expect that something that tries to `PUT /bar` would get a `405 Method Not Allowed`, but instead with http4s 0.6.4 we get `404 Not Found`. I'd love to open a PR for this but it's not immediately evident where this logic lives or how to fix it. (We've made things work on a resource-by-resource basis with `case _ @ _ -> Root / "healthcheck" => Task.now(Response(status = Status.MethodNotAllowed))`.)

Any thoughts?

Thanks for reading,
Will

**Comment by rossabaker** [comment]
The http4s-dsl is straight pattern matching.  There's no central route registry, so there's no way to tell "it matched except for the method."

It is nearly possible to write a middleware to resubmit a request with other methods to construct a 405 with a correct Allow header.  The problem is that the signature is `Task[Option[Response]]` instead of `Option[Task[Response]]`, so the task needs to run to determine whether the request was defined.  

An `Option[Task[_]]` can be sequenced into a `Task[Option[_]]`, but not vice versa.  However, this is not the first time this ordering of monads has proven irritating.

I hate to reopen a debate that was put to bed months ago, but: did we get this one wrong?

**Comment by bryce-anderson** [comment]
First things first, sorry @wsh, this comment offers no solution to the problem, just general discussion. We do appreciate you filing an issue: we are trying to iron out these types of issues.

I think this is more of a intrinsic shortcoming of the http4s-dsl: its 'route table' is not subject to inspection. Currently rho would fail to give the desired behavior as well, but it would be relatively simple to modify it to have this behavior (and perhaps it should be) because its route structure can be inspected. I expect any future scalatra-dsl to have the same qualities as rho.

Certainly a middleware could be written that runs GET, POST, etc on a route that returns a ```Option[Task[_]]``` and just marks a check of it gets a ```Some[Task[_]]```, but that is an ugly solution that would fail in the situation of custom methods or essentially anything we don't explicitly fire at the route to see what sticks. 

Note that I'm not necessarily against going back to ```Option[Task[_]]```, but this feels like a weak justification.

**Comment by rossabaker** [comment]
Here is some prior art from a similar DSL:
https://github.com/unfiltered/unfiltered/tree/master/directives

Something like that would preserve the spirit of extractors and generate a 405, but it would not generate an `Allow` header.

**Comment by chris-martin** [comment]
Just weighing in with my rambling two cents... I just started using http4s and immediately made the mistake of not sending 405s correctly, starting digging for what the recommendation was, and found this issue.

Currently I'm doing something like this:

```scala
HttpService {
  case req @ method -> Root =>
    method match {
      case POST => NoContent()
      case _ => Task.now(Response(status = Status.MethodNotAllowed))
    }
}
```

It's fine for my small use case now, but if I had a significantly larger set of URLs, I'm sure I'd end up writing my own DSL. I really appreciate that the type is `PartialFunction[Request, Task[Response]]`, as basic as possible - I think there are a number of equally valid ways to express this function that depend on the situation - But a simple pattern match with cases like `GET -> Root => ...` will never be one of them and shouldn't be featured in the documentation, because anyone who starts by following that advice will make the same mistake.

On a somewhat related note: I'm puzzled why I have to write `Task.now(Response(status = Status.MethodNotAllowed))` instead of `MethodNotAllowed()` like I can do with the other response codes.

```
org.http4s.Status does not take parameters
           MethodNotAllowed()
                           ^
```

Why is that?

**Comment by chris-martin** [comment]
Ah sorry, I just noticed #66, so I guess my comments are irrelevant.

**Comment by bryce-anderson** [comment]
@chris-martin, Not being able to use ```MethodNotAllowed``` as a response generator is a bug. Thanks for finding it. See PR #255.

**Comment by bryce-anderson** [comment]
__Note:__ I renamed the issue as its not a blaze issue, but a dsl issue.

**Comment by rossabaker** [comment]
Neat: https://github.com/hamnis/http4s-directives

Would love to hear whether @hamnis considers that a successful experiment or not.

**Comment by hamnis** [comment]
@rossabaker I have not yet used it in anger, but I just ported it to 0.17.0-RC2. I have not yet released it, but if anyone wants to take it for a spin, i can do that.

**Comment by rossabaker** [comment]
I don't this fits well into http4s-dsl, but I think it fits very well into the directives style approach.  @iravid has a gist showing how the directives approach relates to a `ContT`.  I think this is something we would want to try to support in that DSL, without supporting in the extractor based http4s-dsl.

**Comment by rossabaker** [comment]
Other alternatives better suited to this use case are mentioned.  I don't think http4s-dsl is the right tool for this job.
