### ISSUE TITLE
magic with `StaticFile.fromResource`

### ISSUE THREAD

**Issue by mr-git** [http4s/http4s#2468]
There is a JVM specific handling of resource lookup in code like:
```
// THIS IS WRONG!!!
case request @ GET -> "docs" /: rest =>
  StaticFile.fromResource(s"/docs/$rest", ecBlocking, Some(request))
    .getOrElseF(NotFound())
```

```
// THIS IS CORRECT
case request @ GET -> "docs" /: rest =>
  StaticFile.fromResource(s"/docs$rest", ecBlocking, Some(request))
    .getOrElseF(NotFound())
```

In above example, `rest` could be value like `/index.html` or `/css/style.css` - important bit is a leading `/`.
The lookup for `/docs//index.html` on different OS-es behaves differently:
* On macOS (JDK 11.0.2), results in found file
* On CentOS (JDK 11.0.2), results in error

**Comment by rossabaker** [comment]
This is a good find, but I'm not sure what we'd do about it at the library level.  Isn't this a matter of how the path passed to `fromResource` is constructed by the app?

**Comment by mr-git** [comment]
It is. I am just thinking on how to make sure, that others do not step on this issue too?
It took me a bit of time to find the cause :)

I wonder, if there is a good way to somehow document this, maybe on `StatisFile#fromResource`?

**Comment by rossabaker** [comment]
I would say there and/or in static.md would be great.

**Comment by diesalbla** [comment]
@rossabaker IMHO, apart from the documentation we should deal with this in the code. For any application developer it can be very tricky to find out an error that only occurs under certain operating systems, since testing and QA in multiple OSs may not be always guaranteed.

I can see two ways to deal with this on the code: 
- Forgiving way: if we know or think that a double forward-slash should always be the same as just one, we could adapt the request to always use one.
- Defensive way: to pick up a fixed format for the input, either always with or always without the  forward slash, and fail if the call does not match that expectation.

**Comment by rossabaker** [comment]
I would prefer to avoid a defensive way that makes it fail on platforms it would otherwise work on.  If we can be more forgiving and more consistent without introducing ambiguity, that seems like a win.
