### ISSUE TITLE
Option to set TLS protocol version and cipher suites

### ISSUE THREAD

**Issue by madanepuri** [http4s/http4s#2499]
Is there a way we can set TLS protocol and CipherSuites while creating server.
We have a requirement to use TLSv1.2 version and remove cipher suites with 128 keys.

Or Is there a way we can pass `SSLEngine` with all the required options while creating the server?

**Comment by RafalSumislawski** [comment]
I think you can do what you need by providing a custom `SSLContext` (it is responsible for creating `SSLEngine`) . See `BlazeServerBuilder#withSSLContext`.

**Comment by rossabaker** [comment]
I think Rafał is correct.  Please let us know if that didn't solve it.

**Comment by geoffreytchew** [comment]
I also need this functionality. The issue I see with the approach recommended above is that you need to pass in an instance of `SSLContext` to `withSSLContext`, which means you need to inherit from `SSLContext`, but the methods I need to override `createSSLEngine` are final. Am I missing something? Since the user is already passing in the client auth flag, it seems to me that the best approach for the consumer of this API would be to allow them to pass in the protocols and cipher suites as well.

**Comment by rossabaker** [comment]
So to be specific, what's missing are:

```
setEnabledCipherSuites(String[] suites)
setEnabledProtocols(String[] protocols)
```

We have a solution for:

```
setNeedClientAuth(boolean need)
setWantClientAuth(boolean want)
```

I don't _think_ anyone would want to customize:

```
setEnableSessionCreation(boolean flag)
```

And nobody should be using:

```
setUseClientMode(boolean mode)
```

An `SSLContext => F[Unit]` would be most flexible, but I think too flexible.  I guess the title says it all: we need to add support for protocol version and cipher suites.

**Comment by rossabaker** [comment]
Would we want access to the list so we can filter them?  I think yes.

**Comment by rossabaker** [comment]
Hmm. These could be separate server settings instead of bolted onto `withSSLContext`.  It doesn't have to be breaking.
