### ISSUE TITLE
Mixing AuthRoutes and HttpRoutes in Router yield a lot of NotFound routes

### ISSUE THREAD

**Issue by Tomahna** [http4s/http4s#2718]
I don't know if it is an expected behavior but It seems, at least to me, a bit weird. Basically when you mix authenticated and http routes inside the same route, most routes become inaccessible.

For example, on Http4s 0.20.4:
```
package example

import org.http4s._
import org.http4s.dsl.io._
import cats.effect.IO
import org.http4s.server.AuthMiddleware
import cats.data.Kleisli
import org.http4s.implicits._
import cats.data.OptionT
import org.http4s.server.Router
import org.http4s.client.dsl.io._
import org.http4s.Method

object Hello extends App {
  case class User(name: String)

  val controller1 = HttpRoutes.of[IO] {
    case GET -> Root / "controller1" => Ok("controller1")
  }

  val controller2 = HttpRoutes.of[IO] {
    case GET -> Root / "controller2" => Ok("controller2")
  }

  val auth: AuthMiddleware[IO, User] =
    AuthMiddleware(Kleisli[OptionT[IO, *], Request[IO], User]{ request => OptionT.liftF(IO(User("bob")))})

  val authController1 = AuthedRoutes.of[User, IO]{
    case GET -> Root / "authController1" as user => Ok(s"hello ${user.name} this is authController1")
  }

  val authController2 = AuthedRoutes.of[User, IO]{
    case GET -> Root / "authController2" as user => Ok(s"hello ${user.name} this is authController2")
  }

  val testApp = Router(
    "" -> controller1,
    "" -> auth(authController1),
    "" -> controller2,
    "" -> auth(authController2)
  ).orNotFound

  println(testApp.run(Method.GET(Uri.unsafeFromString("/controller1")).unsafeRunSync()).unsafeRunSync())
  println(testApp.run(Method.GET(Uri.unsafeFromString("/controller2")).unsafeRunSync()).unsafeRunSync())
  println(testApp.run(Method.GET(Uri.unsafeFromString("/authController1")).unsafeRunSync()).unsafeRunSync())
  println(testApp.run(Method.GET(Uri.unsafeFromString("/authController2")).unsafeRunSync()).unsafeRunSync())

}
```

will yield 
```
Response(status=404, headers=Headers())
Response(status=404, headers=Headers())
Response(status=404, headers=Headers())
Response(status=200, headers=Headers(Content-Type: text/plain; charset=UTF-8, Content-Length: 33))
```

It seems intuitive that it is not a good idea to mix authenticated and non authenticated routes this way as you'll have to fetch user informations multiple time. However how to combine routes so that it works properly does not seem obvious.

**Comment by rossabaker** [comment]
Sorry, I overlooked this when it came in.

It's unusual to use a `Router` where multiple `HttpRoutes` have the same prefix.  It's more common to combine `HttpRoutes` with `<+>` under the same prefix.  In practice, we sort the `HttpRoutes` by the length of the prefix, and then `<+>` them so the longest matching prefix takes precedence.  (This is similar to servlet mappings from ancient times.)

Furthermore, authed routes do not fall through by default.  This is to prevent information leakage: a 401 vs. a 404 reveals information about your resources to an attacker.  To opt out of this behavior, there is `AuthMiddleware.withFallThrough` as an alternative to `AuthMiddleware.apply`.  

I think you'd get more expected behavior if you:

1) Give each argument to `Router` a unique prefix
2) Use `AuthMiddleware.withFallThrough`
3) Reorder so the authed routes compose last, though I'd have to look up what `sortBy` does in a tie.

**Comment by jmcardon** [comment]
Apologies on delay on this.

I've honestly considered changing semantics for this. 

Yes, auth routes composition prevent route scanning and spidering which is a dope feature for helping against intel gathering.

However over the last year and a half there's been a myriad of reports on how unintuitive this behavior is (on gitter primarily). I don't blame the users: there's nothing in the type system that guards against composing routes after auth routes have been sealed, and it's potentially an error (on our end, and by "our" I mean "mine" in terms of taking responsibility) to let them compose them like this.

I do see one of many ways forward though: Authroutes compose well with eachother, but definitely not with other routes, thus, we have a few options:

-  A newtype when you apply authRoutes like in the example `(auth(a))` (in scala's form a case class with anyval or something) that gives you something like a `SealedAuthRoute[F]`, for which we can indicate that it, indeed, _does not_ compose.
- Change the default behavior, and make `.noSpider` an opt-in.

Maybe a vote is in order?

**Comment by Tomahna** [comment]
Hey thanks for your great responses.

@rossabaker unfortunately I can't go for option 1, but 2 and 3 are ok. I found how to compose authed routes in the end using <+>.

A typed solution would probably be great. My point was more about the fact that it does not seem to be clearly documented (or maybe I overlooked it).

If it's fine by you, I'll try to add that to the documentation (hopefully this week end). And then I'll close this issue. (Or leave it open if you want to continue the discussion here)

**Comment by rossabaker** [comment]
Discussions of this fallthrough problem date back to before we had a distinction between `HttpRoutes` and `HttpApp`.  Maybe `AuthRoutes` does fall through and `AuthApp` doesn't?  Those types already express that, and it wouldn't introduce a new concept.  The problem is it would make existing `AuthRoutes` composition less hardened without a breaking change.

@Tomahna Clarification in the docs would be good.  auth.md, on series/0.20, is the best place to look.  There's some commentary on this problem, but it was also hard to recognize because you weren't using `<+>` explicitly, which is where people _usually_ run into this.

**Comment by ChristopherDavenport** [comment]
Well if closed values were HttpApp's that would make things clear in the type system

**Comment by rossabaker** [comment]
Yeah.  There is currently:

```scala
  type AuthedRoutes[T, F[_]] = Kleisli[OptionT[F, ?], AuthedRequest[F, T], Response[F]]
```

I think the newtype is not really a newtype, but an alias that follows the convention:

```scala
  type AuthedApp[T, F[_]] = Kleisli[F, AuthedRequest[F, T], Response[F]]
```

**Comment by ChristopherDavenport** [comment]
Right, so basically when we create those that don't fallthrough, then it should be the app variant. I may be missing something, but it just seems we need to split a method.

**Comment by jmcardon** [comment]
Here's the thing, I do want a newtype precisely because it's opaque, to where you make conscious api decisions to turn it into an `HttpApp` or whatnot via something like `toSealedHttp` or something, that the intent is _clear_ that either requests fall through, or get stuck.
