### ISSUE TITLE
0.20.9 ignores .withIdleTimeout on BlazeServerBuilder

### ISSUE THREAD

**Issue by kbreidenbach** [http4s/http4s#2796]
Since upgrading from 0.20.6 to 0.20.9 I've noticed that `BlazeServerBuilder` ignores the `.withIdleTimeout` setting. 

Even with the following, I get timeouts after the default 30 seconds
```
    BlazeServerBuilder[F]
      .bindHttp(midwayConfig.listenPort, midwayConfig.listenAddress)
      .withHttpApp(finalHttpApp)
      .withIdleTimeout(5 minutes)
      .serve
      .drain
```

**Comment by kevinmeredith** [comment]
Hi @kbreidenbach - could you please give a full example, e.g. github repo w/ a few `curl`'s for reproducing the problem?

> Even with the following, I get timeouts after the default 30 seconds

Which timeout do you get after 30 seconds?

**Comment by RafalSumislawski** [comment]
@kbreidenbach
The default timeouts have been reworked in 0.20.8. Most likely you're hitting the `responseHeaderTimeout` which now defaults to `30 seconds`.

As far as I know, even in 0.20.6 the code sample you've provided won't result in 5 minutes long timeout. Instead you would hit the `responseHeaderTimeout` after `1 minute` (the old default). 

The defaults for `idleTimeout` and `responseHeaderTimeout` have been altered, to have `responseHeaderTimeout` < `idleTimeout`, as it results in better behaviour: sending a 5xx error response on timeout, instead of abruptly terminating TCP connection.

**Comment by kevinmeredith** [comment]
Can this one be closed then, @RafalSumislawski @rossabaker, per https://github.com/http4s/http4s/issues/2796#issuecomment-525922712?
