### ISSUE TITLE
Static content service does not serve static files in an assembled jar

### ISSUE THREAD

**Issue by gpampara** [http4s/http4s#299]
Creating a simple project that has a set of resources in a directory like `src/main/resources/static` results in a working serving of these resources when run from SBT, but when creating an assembled jar (e.g: using sbt-assembly) the resulting jar starts up but is not able to serve the resources.

This is probably related to the URL that is created for the give resources, which is different when served from the classpath.

**Comment by gpampara** [comment]
Sample that illustrates the error: https://gist.github.com/gpampara/e6be20fe86d73f8a1627

Resource is placed in the directory `src/main/resources/dashboard`

**Comment by bryce-anderson** [comment]
This is a problem with how URL's are accepted for resources in the classpath vs the filesystem. The filesystem (at least in my testing) will accept something like /foo//bar.txt while it won't find a resource with the same Url. I think the best thing to do would be to normalize on what each prefix means.

I'll try to get this fixed sooner than later, but as a quick fix, you can change the config pathPrefix to "/" and I suspect your example will work because it will discard a slash.
