### ISSUE TITLE
 Uri replaces semicolons with ampersands in query parameters

### ISSUE THREAD

**Issue by rolandomanrique** [http4s/http4s#3277]
See query param value `add;fgh` is rendered as `asd&fgh`

```
scala> :paste
// Entering paste mode (ctrl-D to finish)
  val ori = "http://domain.com/path?param1=asd;fgh"
  val res = org.http4s.Uri.unsafeFromString(ori).renderString
  assert(ori == res, s"urls don't match:\n$ori\n$res")
// Exiting paste mode, now interpreting.
java.lang.AssertionError: assertion failed: urls don't match:
http://domain.com/path?param1=asd;fgh
http://domain.com/path?param1=asd&fgh
  at scala.Predef$.assert(Predef.scala:219)
  ... 36 elided
```

**Comment by satorg** [comment]
I think the real issue is that the `Uri` parser doesn't recognize a semicolon symbol as an error.
According to the URL encoding rules semicolons should be percent-encoded.
Therefore a valid URL string with a query parameter value with a semicolon should look like:
`"http://domain.com/path?param1=asd%3Bfgh"`
Perhaps it'd be better for the parser to fail on the string `"http://domain.com/path?param1=asd;fgh"` rather than silently replace it with an ampersand.

@rossabaker, WDYT?

**Comment by rolandomanrique** [comment]
@satorg if you try this with other non-encoded url params Uri is able to encode it correctly, I was expecting it to behave the same way and encode semicolon with correct percent-encoded value.

```
scala>   val ori = "http://foo.com/?url=http://test.com?someurl=url"
ori: String = http://foo.com/?url=http://test.com?someurl=url
scala>   val res = org.http4s.Uri.unsafeFromString(ori).renderString
res: String = http://foo.com/?url=http%3A//test.com?someurl%3Durl
```

**Comment by rossabaker** [comment]
@hamnis found the [spec this comes from](https://www.w3.org/TR/1999/REC-html401-19991224/appendix/notes.html#h-B.2.2) in #3349.  I think we are right to respect semicolons as a query string delimiter by default, which I'll argue on that PR.  But I agree that the behavior reported by Rolando is bad: query strings as multimaps are not in the URI or HTTP specs, and we should be careful not to fiddle with them beyond what the specs mandate.
