### ISSUE TITLE
Publish scalafix with the remainder of the project

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#3523]
We just did this manually for 0.20.0, but now we're trying to tie the output version to the http4s version.

**Comment by rossabaker** [comment]
Ping @satorg to make sure this still seems correct.  I think we need to integrate the scalafix build as it stands on master with the main build on series/0.21.x, and then when we publish 0.21.5, we'll also be publishing the scalafixes for 0.21.5 and all subsequent releases.

I'm still a bit more hazy on what the input version should be.  Should it be the last versoin in 0.20?  Or 0.20.0?  Or do we just keep going back to 0.18 forever?

**Comment by satorg** [comment]
This is the first thing I tried to do: keep the input version on 0.18. But it turned out that `Client` [v0.18](https://github.com/http4s/http4s/blob/v0.18.0/client/src/main/scala/org/http4s/client/Client.scala) is very different from `Client` v0.21 – the former is a `final case class` in contrast to newer versions where it is a trait already. So keeping inputs on 0.18 would prevent the rules to work against several important cases like those where some class/trait is derived from `Client`.

I just have checked v0.19 and found out that the `Client` is already a trait there. So perhaps it would be possible to rollback the input version to v0.19 and keep it for a while until it starts to prevent us from writing further rules.

I think I can try to do it in my PR (#3372) to check whether it works or not.

**Comment by satorg** [comment]
So I've tried v0.19.0 as the input version and it looks like there're no problems with this version as for now. I've updated my PR accordingly.

**Comment by rossabaker** [comment]
I spent some time yesterday reading the docs and better understanding the deployment model and what all those projects actually mean.

As long as we don't introduce new dependencies in the rules, it seems like we give users their choice of running from binary or directly from source.  The latter is nice if we catch up on scalafixes after a release.  And when we complete this ticket, we should even be publishing snapshots for people who run them as binary.

I was thinking we'd want the input version to be the last version's output version, so they could be run serially for someone catching up from way back.   But I now think it might be better to make it a maximal span that lets us test all the rules, and we bump it whenever we're scalafixing something introduced after the current input version.

**Comment by satorg** [comment]
So do you think the span from 0.19 (as input) to 0.21 (as output) is large enough for the rules? Because otherwise it'll be necessary to shrink a bunch of meaningful cases from the rules in my PR.

**Comment by rossabaker** [comment]
I think that's good for now.  Note that 0.19.0 was an accidental release (it got tagged while our automation was immature), but it's far back enough to be as good a spot as any.

**Comment by rossabaker** [comment]
Fixed by #3526.
