### ISSUE TITLE
Expose getClientStats in org.http4s.client.asynchttpclient.AsyncHttpClient

### ISSUE THREAD

**Issue by harpresing** [http4s/http4s#3849]
`org.asynchttpclient.DefaultAsyncHttpClient` defines a method `org.asynchttpclient.DefaultAsyncHttpClient#getClientStats` which can be used to obtain the details about the connections the client has made and other interesting stuff.

```scala
val client = new DefaultAsyncHttpClient(config)
client.getClientStats
```

Currently there is no way to call this method from a httpClient which is defined like so:

```scala
val retryPolicy = RetryPolicy[IO] { ... }
val config: DefaultAsyncHttpClientConfig = new DefaultAsyncHttpClientConfig.Builder()...
val sensitiveHeaders: Set[CaseInsensitiveString] = ...

val httpClient: Resource[IO, Client[IO]] = AsyncHttpClient.resource[IO](config).map(Retry[IO](retryPolicy, sensitiveHeaders.contains))
```

Exposing `org.asynchttpclient.DefaultAsyncHttpClient#getClientStats` in `org.asynchttpclient.DefaultAsyncHttpClient` would enable access to very useful functionality.

**Comment by rossabaker** [comment]
Ember achieves this with a subclass of `Client`.  I think the functionality is great, but I'm not thrilled about the subclass design.

A couple other ideas come to mind:

- Add an `apply[F: ConcurrentEffect[F]](org.asynchttpclient.AsyncHttpClient: AsyncHttpClient): Client[F]` method so you can pass your own client, which you can reference for its state.  You'd be responsible for the resource management.
- Add an `allocateWithUnderlying[F[_]](config: AsyncHttpClientConfig): F[((Client[F], AsyncHttpClient), Unit], and probably parallel `resourceWithUnderlying` and `streamWithUnderlying` methods.  Then you could pass in the same config, but it adds a lot of heft to the API for a minor convenience.

I think the first option is simple and composes nicely.  What do you think?

**Comment by rossabaker** [comment]
Also ping @ChristopherDavenport, since he has spent more time in with the subclass.  My experience with it is not being able to fix something while maintaining bincompat, but he has more experience with the ergonomics of actually using it.

**Comment by harpresing** [comment]
Hey @rossabaker, Thanks for your feedback!

The first option does seem very straightforward! I looked at Ember and how it achieves this and did something similar:


```scala
final class ClientWithStats[F[_]](
    private val client: Client[F],
    private val clientStats: ClientStats)(implicit F: Bracket[F, Throwable])
    extends DefaultClient[F] {

  def getClientStats: ClientStats = clientStats

  def run(req: Request[F]): Resource[F, Response[F]] = client.run(req)
}
```

And then in `org.http4s.client.asynchttpclient.AsyncHttpClient`

```scala

  def createClient[F[_]](c: AsyncHttpClient)(implicit F: ConcurrentEffect[F]): Client[F] = Client[F] { req =>
    Resource(F.async[(Response[F], F[Unit])] { cb =>
      c.executeRequest(toAsyncRequest(req), asyncHandler(cb))
      ()
    })
  }

  def allocate2[F[_]](config: AsyncHttpClientConfig = defaultConfig)(implicit
      F: ConcurrentEffect[F]): F[(ClientWithStats[F], F[Unit])] =
    F.delay(new DefaultAsyncHttpClient(config))
      .map(c => (new ClientWithStats[F](createClient(c), c.getClientStats), F.delay(c.close)))

  /** Create an HTTP client based on the AsyncHttpClient library which includes
    * [[ClientStats]]
    *
    * @param config configuration for the client
    */
  def resourceWithStats[F[_]](config: AsyncHttpClientConfig = defaultConfig)(implicit
      F: ConcurrentEffect[F]): Resource[F, ClientWithStats[F]] =
    Resource(allocate2(config))
```

What do you think about this approach? And if this makes sense, could you also guide me on how to refactor `def getClientStats: ClientStats` to something like `def getClientStats: F[ClientStats]`?

Thanks!

**Comment by rossabaker** [comment]
Your `createClient` looks like the `apply` I was thinking of, and I think that's great and should be added to http4s.  (We call similar `apply` on other builders).  I think we should get that into series/0.21, and re-express `allocate` in terms of it.  Would you like to send a PR for that?

`allocate2` and `resourceWithStats` and `ClientWithStats` are good, but not as general.  You want stats, but maybe somebody else wants the signature calculator, or to flush the pool partitions.  We could make it more general by exposing the whole underlying client instead of just the stats, but then there are unsafe methods.  Someone could `close()` the client underneath us, outside our `Resource` management.  Yours exposes a safe subset of the API to your app, to address your needs.  So I think you have a good design, but everything beyond `apply` is better in your app than in the library.

As for `F[ClientStats]`, I don't think you gain much by wrapping that: it will always be the same `ClientStats` instance.  The problem is that those values are not referentially transparent: `getTotalConnectionCount()` may return a different value now than it will a second from now.  If you want to make that functional, you'd want to create a wrapper around `ClientStats` that returns all values in `F`, and just does a bunch of `F.delay(...)` calls to the underlying.

```scala
class HarpeetsSaferClientStats[F[_]: Sync](underlying: ClientStats) {
  def totalConnectionCount: F[Long] = F.delay(underlying.getTotalConnectionCount())
  ...
}
```

And then instead of exposing an `F[ClientStats]`, you expose a `HarpeetsSaferClientStats[F]`.  The difference between this and Ember is that Ember's stats are an immutable type, and AHC's are mutable, so the `F` has to move.  That `HarpeetsSaferClientStats` wrapper could be general enough to be worth adding, but I don't have a good name for it.

**Comment by harpresing** [comment]
Thanks for the great explanation @rossabaker! I'll create a PR to add the `createClient ` as an additional `apply` method and re-express allocate in terms of it. 

I could add `HarpreetsSaferClientStats` and call it `AsyncHttpClientStats` maybe?

**Comment by rossabaker** [comment]
That sounds great to me!  And please open on `series/0.21` branch so it can be released sooner -- it will also be in the 1.x milestones.

**Comment by harpresing** [comment]
Raised a [PR](https://github.com/http4s/http4s/pull/3859) to add an apply method that takes in an `AsyncHttpClient`.
