### ISSUE TITLE
Bringing back `orElse`

### ISSUE THREAD

**Issue by bryce-anderson** [http4s/http4s#387]
Everyone misses it. Even I'm missing it at places. I propose we implement `orElse` by examining the `Response` for `Status.NotFound` and then trucking on. It works pretty well with rho, here is the code:
```scala

implicit class OrElseSyntax(val service: HttpService) extends AnyVal {
  def orElse(service2: HttpService): HttpService = Kleisli { req: Request =>
    service(req).flatMap {
      case resp if resp.status == Status.NotFound => service2(req)
      case resp => Task.now(resp)
    }
  }
}
```

I don't know if it should be a syntax or if we should make a custom `Kleisli`.

**Comment by ShengC** [comment]
There are more implicit changes that come with it though...

    BlazeBuild
      .mountService(foo)
      .mountService(bar)
      ....

This used to work in a way that if a request fails to match `foo`, it falls back to `bar` (or the other way around), now one is totally shadowed by the other, which is why `orElse` is absolutely needed, though I would like to also keep the old behavior. I mean it is ok to break the backwards compatibility of api, but behavior change is, in my opinion, bad....

Also - what are the benefits that transforms `HttpService` from `PartialFucntion` to `Kleisli` ? It is some sort of Reader Monad with Monad tranformer, which ideally is suitable in wiring the inputs and outputs of several components together without writing too much boilerplate. In case of `HttpService`, we need `orElse`, not `andThen`, meaning we need a request to be relayed to the other `HttpService` only if the first one fails to match it.

**Comment by ShengC** [comment]
Would also want to add this ...

    implicit class ContramapSyntax(val service: HttpService) extends AnyVal {
      def contramap(f: Request => Request): HttpService = {
        Service.lift { req: Request =>
          service(f(req))
        }
      }
    }

It can be further generalized to `Service`. Goal is to keep the api as backwards compatible as possible .

**Comment by bryce-anderson** [comment]
I believe this is closed.
