### ISSUE TITLE
Unable to serve 404 response

### ISSUE THREAD

**Issue by ajevans85** [http4s/http4s#416]
Whenever I try to serve a `404 response` the specified body is ignored and instead the below response returned:

```
404 Not Found.
```
With the below example I would expect to see the response "My Custom Body"
```
 HttpService {
    case GET -> Root => homePageController.view
    case _ => NotFound("My Custom Body")
}
```
I am running `http4s` `0.10.0` with the service mounted on `Blaze` at `/`. Changing the response to anything other than `NotFound` correctly renders the given body.

One interesting thing is running the service through the `org.http4s.server.MockServer` in a unit test returns the expected result.

**Comment by bryce-anderson** [comment]
That is annoying. The problem you're having is part of a larger debate about the internal representation of a route. [Here](https://github.com/http4s/http4s/pull/392) is just one issue on the topic; there are a few others if you care to dig.

Normally you would define a [`Fallthrough`](https://github.com/http4s/http4s/blob/master/server/src/main/scala/org/http4s/server/Fallthrough.scala) instance that would preserve your custom 404, should no other paths match. Such a default unfortunately doesn't exist at the current time. The second part of the problem is in the [`Router`](https://github.com/http4s/http4s/blob/master/server/src/main/scala/org/http4s/server/Router.scala) that blaze uses for mounting: it doesn't allow the use of a custom `Fallthrough` typeclass so any 404 response will be overridden by the default that you're seeing.

Sorry there are no solutions in this post. I'll see what I can do when I get some time if @kryptt doesn't address it first.

**Comment by rossabaker** [comment]
Two thoughts come to mind:

1. Because `BlazeBuilder, [creates a router](
https://github.com/http4s/http4s/blob/82278a83640fe1bc1a0dd585968f7bf6266c5d18/blaze-server/src/main/scala/org/http4s/server/blaze/BlazeServer.scala#L103), it should be configurable with a `Fallthrough[Response]`.  (So should `Router.apply`).
 
2. Is our default `Fallthrough[Response]` the correct one?  Good arguments were made for both status code and a special sentinel, which is one reason it's modeled as a type class.  I would measure "correct" as "least surprising," and this issue is one demerit for our choice.

**Comment by kryptt** [comment]
This is a bug, it should be accepting his 404 over the fallthrough we provide.
