### ISSUE TITLE
Update naming for header methods on requests

### ISSUE THREAD

**Issue by Daenyth** [http4s/http4s#4188]
The putHeaders/withHeaders methods are confusing for multiple people.

Let's deprecate them and add `addHeaders` and `replaceHeaders` methods respectively. Those names have immediately-obvious semantics.

**Comment by rossabaker** [comment]
Generally `:+1:`, but I'd have to look up whether `replaceHeaders` replaces all headers or corresponding headers.

**Comment by Daenyth** [comment]
Would there be another naming to make it more clear? `replaceAllHeaders` perhaps?

**Comment by hamnis** [comment]
Interesting enough we already have a deprecated `replaceAllHeaders` in `Message.scala`. It was deprecated in 0.20

**Comment by rossabaker** [comment]
There are a lot of ways to do this, so let's try to be a bit more rigorous in our definitions.

1. Some headers are _recurring_ (e.g., `Accept`), and some are _singletons_ (e.g., `Content-Length`).  A recurring header can have multiple instances.  A singleton header only sensibly has one. 
2. Every recurring header can be combined into a single header by joining their values with a comma, _except_ `Set-Cookie`, because our forebears hated us and wanted us to be unhappy.
3. The semantics depend on the key.

I'm going to intentionally avoid our existing names for things here, because I can't remember what the damn things do.  But there are several possible implementations of `(a: Headers, b: Headers) => Headers`.  Which ones do we want, and what should they be called?

1. Append `a` to `b`, regardless of semantics.
2. Combine headers by key in `a` and `b`, joining duplicates with a comma, regardless of semantics.
3. Replace singletons from `a` with `b`.  Append recurring headers from `b` to `b`.  Keep other headers from `a`.
4. Replace singletons from `a` with `b`.  Combine recurring headers by key in `a` and `b`.  Keep other headers from `a`. 
5. Replace all headers from `a` with `b`.  Keep other headers from `a`.
6. Return `b`
7. ???

**Comment by Daenyth** [comment]
I naively thought that option 5 + option 6 would cover everything people needed. I had no idea headers were that complicated.

I do think it's likely that others are in the same boat as me, in terms of understanding.

For reference, popular libraries like `requests` in python more or less just expose headers as a `Map` which you can add to. I think *most* of the time that serves well enough.

**Comment by rossabaker** [comment]
Operations 1, 5, and 6 don't require any nuanced understanding of recurring vs. singleton.

In today's nomenclature:
* `withHeaders` is 6.
* `putHeaders` is 3.

For more fun:

* `get(HeaderKey.Extractable)` exists and is harmonious with 3/4
* `get(CIString)` exists and is harmonious with 1/5/6
* `get(Set-Cookie)` exists because the spec authors hate us

**Comment by rossabaker** [comment]
I think we have a reasonable solution now in series/0.22.

**Comment by Daenyth** [comment]
What's the state of the methods in 0.22 and forward? Is it changing from 0.23 to 1.x?

**Comment by rossabaker** [comment]
I'm not aware of any active effort to change them from 0.23.  Is there something you'd still like to see?
