### ISSUE TITLE
Extract parsers into module below core

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#4733]
Related to @bblfish's work in #4716: can we extract a sensible parser module to sit beneath http4s-core and share with others?

Why:
* akka-http uses parboiled2.  That's will be an obstacle to their Scala 3 support, and they might be able to reuse our work.
* If they can reuse our work, we'd have more eyes on it and probably catch some latent bugs in our work, and have shared maintenance moving forward.

Why not:
* Our core model is not shared with anybody else, and we parse to a model.  What exactly is it parsing to if http4s-core sits on top of it?  

Realistically:
* It's probably limited to a few RFC helpers?  Still not insubstantial, but not exactly All The Headers.

**Comment by bblfish** [comment]
I had the following sketch in mind.
An HTTP parser is at base a function `parse: ByteSeq => example.lib.HttpHeader`
One could split this in two:

```scala
def syntaxParse: ByteSeq => shared.HeaderStructure
def semanticParse: shared.HeaderStructure => example.lib.HttpHeader
 ```

The syntax layer is something like [Rfc8941Types](https://github.com/co-operating-systems/Reactive-SoLiD/blob/master/src/main/scala/run/cosy/http/headers/Rfc8941.scala#L103). 

Different implementations then essentially provide functions for the second interpretation step `semanticParse`, though my guess is a lot could be re-used across implementations.
This would be maps of header names to functions, each with different range depending on the domain.  That looks like a dependent Sum.

I would love to be able to point JS and Java devs to tools they can go to for Signing Http Messages written in Scala :-) I will also need to write clients in the browser where Akka is clearly too heavy. Next I'll try using this for [Signing Http Messages](https://tools.ietf.org/html/draft-ietf-httpbis-message-signatures-03) which depends on RFC8941.

**Comment by rossabaker** [comment]
Created a though experiment at #4745, so we're talking about something more concrete.

**Comment by jrudolph** [comment]
@rossabaker thanks alot for evaluating the possibility of sharing parsing logic. I also had a quick look into how that would look.

Under the assumption that each user of the library would provide their own model, what would these parsers parse to? It would either have to be an intermediate model or some kind of GADT which can then be postprocessed into the final model. In #4745, you showed that for a simple product type but we will also need sum/record types.

Given that header parsing is not really difficult semantically, right now the parsers consist more of glue code than actual parsing code. A lot of glue code would still be necessary to make use of those shared parsers.

So, as you say, the main benefit of sharing parsing rules would be to agree on semantics rather than on saving us from some work.

Could it make sense to just provide a library to parse primitives? Or is there another way of consuming shared parsers that I am missing?

**Comment by bblfish** [comment]
> It's probably limited to a few RFC helpers? Still not insubstantial, but not exactly All The Headers.

**Comment by bblfish** [comment]
@jrudolph wrote
> what would these parsers parse to? It would either have to be an intermediate model or some kind of GADT which can then be postprocessed into the final model.

I think the idea is that they could parse to [RFC8941: Structured Field Values for HTTP](https://tools.ietf.org/html/rfc8941).

**Comment by mnot** [comment]
See [this](https://mnot.github.io/I-D/binary-structured-headers/) (still very rough).

**Comment by bblfish** [comment]
I have published initial snapshot library of "Signing HTTP Messages" for Http4s and Akka  here
https://oss.sonatype.org/content/repositories/snapshots/net/bblfish/crypto/

**Comment by armanbilge** [comment]
Closing for reasons described in https://github.com/http4s/http4s/pull/4745#issuecomment-1093683127 and because we have 314 other issues.
