### ISSUE TITLE
Possible Blaze Client Performance Regression in 0.21.23

### ISSUE THREAD

**Issue by djspiewak** [http4s/http4s#4916]
Seeing some anecdotal issues with performance regressions between 0.21.22 and 0.21.23. In particular, it appears to be the blaze-client (and possibly not the server) which is having problems. The symptoms are slightly higher mean response times, and *much* higher tail response times (even the p70s climb, it it's most stark in p95, p99 and p9999s). The regression appears to be on the order of magnitude of 2x in the p99s, and the instability is quite significant.

Working to see if I can get some narrower data on this or even ideally a reproduction.

**Comment by djspiewak** [comment]
Can confirm that the performance regression is real. The general outcome is that the p9999 latency is just about doubled. p50 seems mostly unaffected. We're bisecting snapshots and running production performance stress tests between 0.21.22 and 0.21.23 right now to see if we can find the commit that introduced the regression.

**Comment by djspiewak** [comment]
Current bisection status: the regression was likely introduced in either #4810 or #4812.

**Comment by Baccata** [comment]
After applying some educated dichotomy between 0.21.22 and 0.21.23 and running performance tests against an actual service, I can confirm that https://github.com/http4s/http4s/pull/4810 introduced the regression.

**Comment by djspiewak** [comment]
Additionally, @Baccata was able to confirm that #4815 appears to amplify the regression, bringing the p9999 degradation from 2x to around 3x. This pattern is seen across multiple services which are using http4s-blaze-client, so I don't believe it is in any way usage-dependent.

My recommendation would be that these semantics be made opt-in and configurable. @rossabaker @RafalSumislawski

**Comment by RafalSumislawski** [comment]
In absolute terms, how high are the response times? When you say p9999 increased 3x, is it an increase from 10ms to 30ms, or 100ms to 300ms, or something even bigger? Is the system running under 100% CPU load in the stress tests?

#4810 added starting and IO operation (read), and #4815 added waiting for an IO operation (write) to complete on the execution path before the point in which the result of the request is available. I think we could try moving them to background, in the sense that the response would be made available early, and then on a different thread the connection would enter some intermediate state in which it would be prepared to be recycled back into the connection pool.

Also, in many cases we may be able to reduce the delay introduced by the waiting for the write to complete, by skipping a write if the content is an empty array.

**Comment by Baccata** [comment]
In absolute terms, the 3x is from ~35ms to ~100ms. The service is not running under 100% CPU load (I signed off work so can't check for actual numbers but I can tell you that much)

**Comment by RafalSumislawski** [comment]
Thanks. I'll see if I can reproduce something similar locally.

**Comment by RafalSumislawski** [comment]
I think I finally found something. In most tests I observe comparable latencies with 0.21.22 and 0.21.23. And in these tests the p9999 is basically a garbage collector benchmark. With the right parameters I managed to create a test scenario in which 0.21.23 pushes the GC to the wall leading to p9999=660ms, while in the same scenario 0.21.22 has p9999=57ms. I can't be sure if that's what is happening in your case, but I think it's worth a shot.

Trying to explain this difference I found a temporary memory leak in blaze-client 0.21.23. It leaks ~2.5kB per request, for the duration of idleTimeout. Through this leak 0.21.23 can put additional pressure on the GC leading to increased latency.

I've prepared a patch https://github.com/RafalSumislawski/http4s/commit/74c2fda81456ea10f9c00a86ce2566a838707d0e which prevents the mem-leak and improves latency in the aforementioned test. It's not a proper solution to the problem, but it should be enough to verify if what I found is the same thing that's troubling your application.

@djspiewak / @Baccata Could you try using http4s built from that commit and see if it solves the problem in your case?

**Comment by Baccata** [comment]
@RafalSumislawski thanks, I'll have a go this week !

**Comment by Baccata** [comment]
@RafalSumislawski so we tested your patch this morning on two different services.

* On one of the services, stats are similar enough to what we had in 0.21.22 that we'd be comfortable upgrading to a version containing your patch. 
* The other service has stricter expectations with regards to latency, and tests accordingly. We did definitely notice an improvement compared to 0.21.23, but it's not back to what it was in 0.21.22. 

Here are some graphs showing the differences in a gatling simulation : 

#### 0.21.22

<img width="1383" alt="Screenshot 2021-07-05 at 11 31 35" src="https://user-images.githubusercontent.com/4439335/124451338-92e80480-dd85-11eb-89ae-4b3d8819bcf7.png">
 
#### your patch 

<img width="1383" alt="Screenshot 2021-07-05 at 11 31 35" src="https://user-images.githubusercontent.com/4439335/124451196-6fbd5500-dd85-11eb-85ed-8a777fd14ccd.png">

**Comment by RafalSumislawski** [comment]
@Baccata would you be able to collect some garbage collector statistics from 0.21.22 and the version with the patch? I'm trying to understand if the difference is still caused by GC or if I should look elsewhere. It would be perfect if you could provide GC logs from both runs. But if that's not possible, some simple statistics like:
- number of young/old garbage collections
- an example (or better an average) young/old GC time
- the size of the heap (if you're letting the JVM adjust the size)
- and utilisation of the heap (or better utilisation of each heap region)
would also be useful.

By the way which JVM version and which GC are you running?

**Comment by Baccata** [comment]
@RafalSumislawski sorry for the delay ! Here's a few answers : 

* the service in question is using zulu-openjdk 11, with default GC 
* the jvm opts are as follows, on a docker container that has 4GB memory reserved, 

```
    -XX:+AlwaysPreTouch
    -XX:MetaspaceSize=256M
   -XX:MinRAMPercentage=50
   -XX:MaxRAMPercentage=80
``` 

More importantly, we've realised that the particular simulation we've used to produce the graphs in my previous message may be impacted by external noise that would skew the numbers. We managed to get a good run, then a couple bad ones, without changing the setup. 

We're gonna run the simulation a few more times later (hopefully) today, see if we get more consistent successes (or failures), and will compare against 0.21.22. If we get consistent successes with 0.21.22, and failures with your patch in place, we'll share some GC/heap stats. 

In the meantime, the first service against which I tested your patch definitely demonstrated improvements over 0.21.23. So that's positive 👍

**Comment by rossabaker** [comment]
This regression caused some concern at my new job, but I haven't been there long enough to produce any kinds of numbers.  Our RCs are getting old, and there's a lot of momentum at $WORK and in the community to do the final releases.

Would everyone be comfortable doing a round of releases with this patch, including final for 0.22 and 0.23?

**Comment by rossabaker** [comment]
And also, thank you both for pursuing and testing this.  I'm delighted to see the progress and collaboration!

**Comment by djspiewak** [comment]
> Would everyone be comfortable doing a round of releases with this patch, including final for 0.22 and 0.23?

IMO this is the correct approach. 0.21 has a stable release which contains this regression, so 0.22 and 0.23 will certainly be no *worse*.

**Comment by Baccata** [comment]
> Would everyone be comfortable doing a round of releases with this patch ...

I think so

> ... including final for 0.22 and 0.23? 

I'm sorry to say I cannot confidently say "go ahead with finals" at this time, because the perf environment tied to the particular service that exhibits weird behaviour is being used for another investigation at the moment, and we haven't been able to confirm (nor invalidate) whether the weird behaviour in question is tied to http4s at all. We should be able to resume tomorrow.  

But since Daniel's already answered, I'm sure he'll happily take the blame if things go south 😄

**Comment by djspiewak** [comment]
> But since Daniel's already answered, I'm sure he'll happily take the blame if things go south 😄

I mean, that would have happened anyway… :-P

**Comment by rossabaker** [comment]
I also feel fairly confident in our ability to patch it binary-compatibly. Let's move forward.

**Comment by RafalSumislawski** [comment]
I hope you all do realize that the current "patch" (RafalSumislawski@74c2fda) is more of an experiment designed to verify my hypothesis, rather than a proper fix of the issue. That being said a reserved some time today to work on a fix, so stay tuned.

I have no strong opinion on whether or not to do the stable release.
