### ISSUE TITLE
[0.23] Error parsing address from Jetty with ipv6

### ISSUE THREAD

**Issue by perok** [http4s/http4s#4952]
Running http4s 0.23.0-RC1 with Jetty and IPv6 crashes with the following:

```
ERROR org.http4s.servlet.Http4sServlet - Error processing request
java.util.NoSuchElementException: None.get
```

The issue is that Jetty returns the following addresses:

```
req.getLocalAddr -> "[0:0:0:0:0:0:0:1]"
req.getRemoteAddr -> "[0:0:0:0:0:0:0:1]"
```

This crashes the following parsing `IpAddress.fromString(req.getRemoteAddr).get`in Http4sServlet. Is brackets on the address considered an error on the parsing side or on Jetty's side?

A temporary workaround for us is to force ipv4 with `-Djava.net.preferIPv4Stack=true`.

**Comment by rossabaker** [comment]
[hangs head in shame for using `.get`]

This looks related to https://github.com/eclipse/jetty.project/issues/1503.  Rather than say Jetty or ip4s is wrong, I'd say http4s is wrong for assuming they agree.  I think we should strip brackets before that call.

Arguably, ip4s should handle both, like the Java APIs.  But that's up to @mpilquist.

**Comment by mpilquist** [comment]
No strong opinions. At first glance, I'd say that bracketed v6 is part of the URI RFC, not IPv6, and hence the brackets should be removed prior to calling `IpAddress.fromString`. But I very well may be missing something and it may be more practical to handle it in ip4s regardless. Let me know what you think.

**Comment by rossabaker** [comment]
I think [this Jetty comment](https://github.com/eclipse/jetty.project/issues/1503#issuecomment-760995044) summarizes the grim situation from the specs.  Since I used it as a drop-in for the Java libraries, the argument that it should be compatible with the Java libraries seems good to me.

Regardless, I think we should fix it here and not rely on the generosity of ip4s' parser.

**Comment by mpilquist** [comment]
😱

**Comment by rossabaker** [comment]
@san-coding I don't think anybody has taken this up, if you're still looking for one.

**Comment by san-coding** [comment]
> @san-coding I don't think anybody has taken this up, if you're still looking for one.

Thanks ross, yes I am looking forward to contribute

**Comment by san-coding** [comment]
@rossabaker , I have figured out that I have to change this file [servlet/src/main/scala/org/http4s/servlet/Http4sServlet.scala](https://github.com/http4s/http4s/blob/453221b56ef9b6ec9118fdad3462725afef11b83/servlet/src/main/scala/org/http4s/servlet/Http4sServlet.scala) , could you help me out on what changes I should make

**Comment by san-coding** [comment]
Is this where I should make changes ?
https://github.com/http4s/http4s/blob/453221b56ef9b6ec9118fdad3462725afef11b83/servlet/src/main/scala/org/http4s/servlet/Http4sServlet.scala#L112-L119

**Comment by rossabaker** [comment]
I'm sorry. That `stripBracketsFromAddr` already fixes this, and it wasn't linked, so I neglected to close it.  I'll look for another one.

**Comment by san-coding** [comment]
> I'm sorry. That `stripBracketsFromAddr` already fixes this, and it wasn't linked, so I neglected to close it. I'll look for another one.

Ohh okay , thanks
