### ISSUE TITLE
Update `Origin` header to current standard or document decision not to do so

### ISSUE THREAD

**Issue by bplommer** [http4s/http4s#5009]
The [model for the `Origin` header](https://github.com/http4s/http4s/blob/main/core/src/main/scala/org/http4s/headers/Origin.scala) allows a non-empty list of hosts, citing [RFC 6454](http://tools.ietf.org/html/rfc6454#section-7) but the [current standard](https://fetch.spec.whatwg.org/#origin-header) allows only one host, noting that this supplants the definition in the RFC.

I can think of the following options:

1. Update the models to only allow one host, and have the parser handle extra hosts by:
  a. ignoring them
  b. raising an error
2. Add a third subtype to the model, `SingleHost`, with a comment noting that `HostList` is not spec-compliant
3. Headers are type-classes now! Why not provide strict or permissive versions? 
4. Leave the behaviour as is, with a comment added to document the decision.

I would favour option 1a, but my view obviously doesn't deserve any special weight.

**Comment by rossabaker** [comment]
Here is a [discussion of the discrepancy](https://lists.w3.org/Archives/Public/www-archive/2012Jun/0001.html).

Interestingly, consecutive equal values are disallowed in the old RFC, but I'm going to pretend that I didn't read that.

Let's change the model in main.  What happens if a value is a valid host followed by gibberish?  Would we disallow that, but ignore valid trailing hosts?  Or would this parser, unlike most others, tolerate trailing gunk?  I'm leaning toward 1b.

I'm trying to think of other headers whose value types are defined in the header's companion instead of the root `org.http4s` package.  But I'm not sure what we'd call it besides `Origin`, and having an `Origin` value and a `headers.Origin` header would be dreary.  Our cousins at akka-http get away with it by calling the value `HttpOrigin`, but we got rid of the `Http` prefix from our common Spray lineage a long time ago.
