### ISSUE TITLE
Dependabot alerts from yarn.lock

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#5031]
I don't know how to fix any of these, and they popped up immediately on merge of Scala.js support: https://github.com/http4s/http4s/security/dependabot

* Upgrade glob-parent to version 5.1.2 or later.
* Upgrade sockjs to version 0.3.20 or later.
* Upgrade yargs-parser to version 13.1.2 or later.

I don't have a good grasp of what's main and what's tests, but I'd also like to clean it up so we don't ignore meaningful ones later.

/cc @armanbilge

**Comment by armanbilge** [comment]
I can't see them at the link you sent actually, but you can ignore these, the same issue came up with fs2. These are all dev/test dependencies, and are quite probably not even used. Unfortunately this is due to upstream issues with `ScalaJSBundler`.

For the record, all of our JS implementations rely only on APIs available in the browser or Node.js and absolutely no third-party packages.

**Comment by rossabaker** [comment]
So if we ever see these in a yarn.lock, it's safe to dismiss them, until someone adds a third-party dependency to main code?

**Comment by armanbilge** [comment]
Yep, this is how it is for many pure JS projects AFAICT. Crazyness.

**Comment by rossabaker** [comment]
Good grief.  

Well, then I think we're prepared for liftoff after fs2-3.1 releases.
