### ISSUE TITLE
Change Server and Client Logger default redactHeadersWhen to include any header with "token"

### ISSUE THREAD

**Issue by Lasering** [http4s/http4s#6104]
As the title says. For example for Server Logger the apply would be:
```scala
def apply[F[_]: Async](
    logHeaders: Boolean,
    logBody: Boolean,
    redactHeadersWhen: CIString => Boolean = (name: String) => Headers.SensitiveHeaders.contains(name) || name.toString.toLowerCase.contains("token"),
    logAction: Option[String => F[Unit]] = None,
)
```

Or even better create a
```scala
def defaultRedactHeadersWhen(name: CIString): Boolean =
    Headers.SensitiveHeaders.contains(name) || name.toString.toLowerCase.contains("token")
```
and then
```scala
def apply[F[_]: Async](
    logHeaders: Boolean,
    logBody: Boolean,
    redactHeadersWhen: CIString => Boolean = defaultRedactHeadersWhen,
    logAction: Option[String => F[Unit]] = None,
 )
```
I can make a PR.

**Comment by ChristopherDavenport** [comment]
Is this a standard? Some people might use it, but it's unclear to me why this should be a default.

**Comment by rossabaker** [comment]
`SensitiveHeaders` is also shared by `FollowRedirect` for which headers are omitted when following a redirect to a different authority.  This proposal wouldn't affect that, because it's an addition to the `Set` for the logger only.  But is having the Logger be more aggressive in redaction okay?  I _think_ so, but throwing that out there.

**Comment by isomarcte** [comment]
I'm of the opinion we should change this to an allow list which includes all the standard headers which are known to be non-sensitive. It's too easy to shoot yourself in the foot with a deny list of headers since there are _so many_ sensitive extension headers.

FWIW, I have the list built out here already: https://github.com/errors4s/errors4s-http/blob/series/1.1.x.x/http4s/src/main/scala/io/isomarcte/errors4s/http4s/headers/AllowedHeaders.scala

**Comment by rossabaker** [comment]
Should that same allow list be used by FollowRedirect?  Again, changing that could break a lot, unlike logging.

**Comment by Lasering** [comment]
At least for logging I would like to see custom request headers the application/client might be using which that list would redact.

**Comment by isomarcte** [comment]
@Lasering I think the encoding should be still be predicate based, e.g. `CIString => Boolean`, or perhaps `CIString => Option[CIString]` to permit a transform. That would allow people to continue to use deny lists if they wanted, but we could have the default be an allow list.

It's only the default that I think should be more restrictive.

**Comment by rossabaker** [comment]
I'm not at my sharpest today.  What is the difference between those two signatures?  (I think the first one was meant to be `CIString`...)  It seems like there's agreement on a predicate, and disagreement on what the default should be.

**Comment by Lasering** [comment]
> I think the first one was meant to be `CIString`

Yes. Fixed it.

**Comment by isomarcte** [comment]
@Lasering I'm fine with that change. I guess what I getting at is that if we move to an allow list, then that would replace this change, which is why I brought it up in this context.

**Comment by ChristopherDavenport** [comment]
@Lasering Would you like to run with this? Seems like a pretty straight forward change, and there seems to be agreement.

We can find someone to do this quick change, if you'd prefer we take it.

**Comment by Lasering** [comment]
@ChristopherDavenport done
