### ISSUE TITLE
Scaladoc has broken external links.

### ISSUE THREAD

**Issue by tpolecat** [http4s/http4s#648]
At least some external links in scaladoc are broken. See [Request](http://http4s.org/api/0.15/#org.http4s.Response) and click on `Process` from the signature for `bodyAsText` and it craps out because no such host. I couldn't find a declaration anywhere in the build that associates streams with that host, but I didn't look very hard.

**Comment by rossabaker** [comment]
Yes, we have some slop there.  We run 2.10 as the primary build so we don't pick up any 2.11isms, but the unidoc only runs as 2.11 because the macros interfere with it on 2.10.  So there are errors in the scaladoc that aren't exactly in anybody's face.

Running as 2.11.x and cleaning up the scaladoc related warnings should fix this, and similar, issues.

**Comment by rossabaker** [comment]
If there's a scaladoc doctor in the house, I need help.  I gave up and just delinked a bunch.  Frustrations:

* References to values with backticks seem to work if I drop the backticks.  lolwut?
* I can't deduce the pattern for when I need FQCN and when I don't.
* I couldn't seem to link to third parties.  That makes sense.  Do I vaguely recall there's a way to say where those live?  I'm especially disappointed that I can't link to javadocs.
* Linking to methods, especially ambiguous ones, seems hit and miss.
