### ISSUE TITLE
Deprecate methods that take `F[Request[F]]` as a parameter

### ISSUE THREAD

**Issue by danicheg** [http4s/http4s#6650]
As a further step in #3345 @satorg [has suggested](https://github.com/http4s/http4s/issues/3345#issuecomment-817362069) deprecating methods that take `F[Request[F]]` as a parameter. I propose to discuss this suggestion here.

**Comment by satorg** [comment]
I just think that methods taking `F[Request[F]]` as a parameter are although harmless but quite useless.
Since `Request[F]` is supposed to be pure and safe then there are no real need to keep those method as first-class citizens of `Client`. Having same methods that take just `Request[F]` it is unlikely that they can be somehow optimized for `F[Request[F]]`. They can be implemented in a form of extension methods though, if necessary.

**Comment by danicheg** [comment]
This makes sense to me. So I've opened #6651.
