### ISSUE TITLE
Helper for X-Forwarded-For header

### ISSUE THREAD

**Issue by ceedubs** [http4s/http4s#681]
`Request` has a `remote` method on it for grabbing the IP address. It would be nice if there were a helper (as either a separate method or as middleware) to check the `X-Forwarded-For` header and fall back to the remote IP. This is a common pattern when load balancers are used.

**Comment by rossabaker** [comment]
Jetty implements this as a [request customizer](http://www.eclipse.org/jetty/documentation/9.4.x/configuring-connectors.html#_proxy_load_balancer_connection_configuration).  Tomcat does this as a [valve](https://tomcat.apache.org/tomcat-8.0-doc/config/valve.html#Remote_IP_Valve).  These are both roughly equivalent to a middleware.

A middleware might not be ideal because it would look for this header whether the connection info is ever requested or not.  Making the attribute lazy, along with a middleware, might be the way forward here?

**Comment by rossabaker** [comment]
This might require standing on one's tip-toes, but I think this fruit can be reached without a stepladder.
