### ISSUE TITLE
Questions about vulnerability GHSA-54w6-vxfh-fw7f

### ISSUE THREAD

**Issue by Disseminator** [http4s/http4s#6911]
Hi！
The vulnerability [GHSA-54w6-vxfh-fw7f](https://github.com/advisories/GHSA-54w6-vxfh-fw7f) points out ：
![image](https://user-images.githubusercontent.com/92628000/211131728-1a2cc3be-5a4e-4308-a00f-9591ce616e7c.png)
However, I used the 0.23.16 version of Http4s to do a verification and found that the following two methods of handling "User Agent" had no difference：
- QuickstartRoutes.scala:
![image](https://user-images.githubusercontent.com/92628000/211131844-f1ec54a7-a06a-43f5-9f91-3e59d0831162.png)
- Customize the Get request of "user agent":
![1e809e1a-bf09-44e6-903b-869381402c70](https://user-images.githubusercontent.com/92628000/211131895-e74cad3d-bd43-460f-8270-09dda6b99c61.png)
- Both are correctly processed and output:
![image](https://user-images.githubusercontent.com/92628000/211132215-a907c094-cdbf-4f53-93f0-064b6e6bcb88.png)
So I would like to ask how to reflect the harm of this vulnerability. Thank you！

**Comment by rossabaker** [comment]
There exist malicious values for those headers that can result in a fatal error in your second usage.  If you trust all clients and servers you communicate with, you need not worry.  If you are exposed to public requests or can be directed to fetch from arbitrary servers, and also parse those headers, you are at risk.

We have unit tests that demonstrate the error, but withheld them to give people extra time to patch or otherwise mitigate.  We will publish them in due time for full transparency and to avoid a regression.

Thank you for taking the vulnerability seriously!

**Comment by Disseminator** [comment]
I want to know how to exploit this vulnerability, thank you!
