### ISSUE TITLE
log4cats dependency

### ISSUE THREAD

**Issue by gmkumar2005** [http4s/http4s#7300]
My code fails to compile after upgrading to 1.0.0-M40 from 1.0.0-M39
Apparently there is a hard dependency on log4cats is introduced. 

```
    val clientResponse: M[OlpResponse[OAuthToken]] = clientResource.use { client =>
      val redirectClient =
        MiddleWareLogger(true, true, _ => false)(FollowRedirect[M](5, _ => true)(client))
      given c: Client[M] = redirectClient
      OlpClient[M].auth.getAccessToken
    }
```
Above code fails to compile. 
I am using ScribeLogger and it works fine in 1.0.0-M39. When upgraded to 1.0.0-M40 it fails to compile with below error.
```
missing argument for parameter evidence$2 of method apply in object Logger: (implicit evidence$1: cats.effect.kernel.Concurrent[M], evidence$2:
  org.typelevel.log4cats.LoggerFactory[M]): org.http4s.client.Client[M]
```

**Comment by danicheg** [comment]
> Apparently there is a hard dependency on log4cats is introduced.

Could you show us what version of `log4cats` you're using? I guess it's `v2.5.0` or older. In that case, fixing your local log4cats version should help.

**Comment by gmkumar2005** [comment]
I am using scribe. log4cats. I use scribe. 

```
val loggingLibs = Seq(
  "com.outr" %% "scribe-slf4j2" % scribeVersion,
  "com.outr" %% "scribe-cats"   % scribeVersion,
  "com.outr" %% "scribe"        % scribeVersion
)
```

**Comment by danicheg** [comment]
Ah, sorry, I'm completely wrong 🙈 

> missing argument for parameter evidence$2 of method apply in object Logger: (implicit evidence$1: cats.effect.kernel.Concurrent[M], evidence$2:
  org.typelevel.log4cats.LoggerFactory[M]): org.http4s.client.Client[M]

`scalac` said that you need to provide a `LoggerFactory` instance. You may glance at the `log4cats` docs https://github.com/typelevel/log4cats/#logging-using-capabilities for the details. A grab-and-go solution is the following:
```
import org.typelevel.log4cats.LoggerFactory
import org.typelevel.log4cats.slf4j.Slf4jFactory

implicit val logging: LoggerFactory[IO] = Slf4jFactory[IO]
```

**Comment by gmkumar2005** [comment]
I don't want to use log4cats. I am already using scribe. Http4s should not depend on log4cats. It should allow any logger one wants to use.

**Comment by satorg** [comment]
@gmkumar2005 could you clarify please – do I understand correctly that `MiddleWareLogger` is just the renamed `org.http4s.*.middleware.Logger`, isn't it?

> I don't want to use log4cats. I am already using scribe. Http4s should not depend on log4cats.

Let me separate things out:
1. According to its purpose (and as its name suggests), the `middleware.Logger` is supposed to use at least _some_ logging API. Due to several design consideration it happens that **log4cats** has been chosen after all.
2. Before  the `M40` release there was another log library in use, not **log4cats** at all but not **scribe** either. Previously it was privately initialized and silently used without letting anyone know about it. In other words, even though your code above used to compile previously, it didn't benefit from **scribe** for the `MiddleWareLogger` anyway (unless you replaced the backend somewhere else). See also #7122 for more details about that change.
3. Note that `LoggerFactory` from **log4cats** is just an interface. You don't have to use its backed – you can provide an implementation that instantiates a logger from **scribe** as well. Perhaps, there's a ready-to-go implementation somewhere around, but even if not, it should be fairly easy to provide your own. In other words, now there's better control over it in **http4s** comparing to its previous version.
4. Even though **http4s** `v1.0.0-M40` is quite well-developed, it is still in the _milestone_ phase. Unfortunately it means, that breaking changes are possible and can happen from time to time.

**Comment by danicheg** [comment]
@satorg Thank you for such a detailed answer. In my humble opinion, that clarifies the question at most.
So, closing this issue. @gmkumar2005 feel free to ask any other question on the [Discord](https://discord.com/channels/632277896739946517/632286375311573032).

**Comment by armanbilge** [comment]
@gmkumar2005 see also:
- https://github.com/outr/scribe/issues/105

**Comment by gmkumar2005** [comment]
@satorg Thanks for the detailed explanation. Exposing the logging will allow greater control on log level and log formats. In my use case I have scribe implemented. I did not find a LoggerFactory which works with Scribe. As a workaround I have implemented additional logging solution based on log4cats as follows.
``` given catsLogging: LoggerFactory[IO] = Slf4jFactory.create[IO]```
Additionally I had to add the types to the tagless functions. 
@armanbilge  scribe does not provide a ready to use LoggerFactory. I attempted but could not complete it. 
This issue can be closed.

**Comment by armanbilge** [comment]
> @armanbilge scribe does not provide a ready to use LoggerFactory. I attempted but could not complete it.

@gmkumar2005 see:
- https://github.com/outr/scribe/issues/105#issuecomment-1396890854
- https://github.com/typelevel/log4cats/blob/f8d54a78ad91a822f15d4f88612a435a99e761cf/cats/scribe/shared/src/main/scala/io/chrisdavenport/log4cats/scribe/ScribeLogger.scala
