### ISSUE TITLE
"CORS headers were denied" message duplicates by number of services with CORS middleware

### ISSUE THREAD

**Issue by mxl** [http4s/http4s#932]
If there are N > 1 registered services with CORS middleware then [this message](https://github.com/http4s/http4s/blob/master/server/src/main/scala/org/http4s/server/middleware/CORS.scala#L107) is logged N times.

```scala
import java.net.InetSocketAddress

import org.http4s._
import org.http4s.dsl._
import org.http4s.server.ServerApp
import org.http4s.server.blaze.BlazeBuilder
import org.http4s.server.middleware.{CORS, CORSConfig}

import scala.concurrent.duration._

object Main extends ServerApp {

  val cors = (s: HttpService) =>
    CORS(
      s,
      CORSConfig(
        anyOrigin = true,
        anyMethod = true,
        maxAge = 1.day.toSeconds,
        allowCredentials = true
      )
    )

  override def server(args: List[String]) =
    BlazeBuilder
      .mountService(cors(HttpService {
        case POST -> Root / "test1" => Ok()
      }))
      .mountService(cors(HttpService {
        case POST -> Root / "test2" => Ok()
      }))
      .bindSocketAddress(new InetSocketAddress(8000))
      .start
}
```

```
curl http://localhost:8000/test1
```

Log:

> 10:32:20.700 [pool-5-thread-1] INFO org.http4s.server.middleware.CORS - CORS headers were denied for GET /test1
> 10:32:20.728 [pool-5-thread-1] INFO org.http4s.server.middleware.CORS - CORS headers were denied for GET /test1

Message is logged even if service does not exist:

```
curl http://localhost:8000/notExists
```

Log:

> 10:33:59.124 [pool-5-thread-4] INFO org.http4s.server.middleware.CORS - CORS headers were denied for GET /notExists
> 10:33:59.124 [pool-5-thread-4] INFO org.http4s.server.middleware.CORS - CORS headers were denied for GET /notExists
>

**Comment by mxl** [comment]
See https://github.com/mxl/scala-issues/tree/http4s-cors-issue example project (checkout http4s-cors-issue branch).

**Comment by rossabaker** [comment]
Closing this because #931 and #933 are the real problems, but the example is much appreciated in chasing them!

**Comment by mxl** [comment]
This issue is specifically about duplicating "CORS headers were denied" message. I have about 30 http services in my application using CORS middleware and every time when one service receives request this message appears ~30 times in a row and pollutes log.

**Comment by mxl** [comment]
@rossabaker Could you reopen this and track separately because it differs from #931?

**Comment by rossabaker** [comment]
I see. #931 was about whether it should be logged, and this about how many times.

`.mountService(cors(a)).mountService(cors(b))` effectively gets translated to `cors(b) orElse cors(a)`.  A request for a resource in `a` goes through the `cors` middleware while trying to match routes in `b` before again going through the `cors` middleware in `a`.  Not only does this result in multiple logging, it's inefficient if the CORS config is the same for `a` and `b`.

Instead of `mountService(cors(a)).mountService(cors(b))`, I am suggesting something like `mountService(cors(b OrElse a))`.  Since you have 30 services, you can compose them with a `reduce(_ orElse _)`, and wrap that in `cors`, assuming everything has the same CORS config.

**Comment by mxl** [comment]
It's clear to me now. Thanks.
